server:
  port: 8878

datasource:
  drivername: mysql
  user: root
  password: qzzx91112
  protocol: tcp
  host: 127.0.0.1
  port: 3306
  name: douyin_utf8
  args:
    -
      parseTime=True
    -
      charset=utf8

redis:
  port: 6379
  DB: 0

resources:
  video:
    path: D:\Hz_go\github\douyin_mine\video
  picture:
    path: D:\Hz_go\github\douyin_mine\video
    defaultrelativepath: 0\0\default.jpg